#server.port=1111

#spring.datasource.url= jdbc:mysql://localhost:3306/javabatch

#spring.datasource.username=root

#spring.datasource.password=Temp1234

#spring.jpa.hibernate.ddl-auto=create


server:
  port: 1111
  
spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/javabatch
   username: root
   password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myActuator

  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
      
#info:
 # createdBy: Aman Kumar
  #modified: 22June 2022
  
logging:
  level:
    com:
     zensar: debug
   